checks:
    python:
        code_rating: true
        duplicate_code: true

build:
    tests:
        override:
            -
                command: 'nosetests --with-coverage'
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'