"""empty message

Revision ID: 162c0569049c
Revises: 90b724f11869
Create Date: 2016-05-21 15:57:56.149000

"""

# revision identifiers, used by Alembic.
revision = '162c0569049c'
down_revision = '90b724f11869'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_created', sa.INTEGER(), nullable=True),
    sa.Column('date_modified', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.TEXT(), nullable=True),
    sa.Column('password', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
