"""empty message

Revision ID: 90b724f11869
Revises: 58d7e7735cb0
Create Date: 2016-05-21 15:48:18.395000

"""

# revision identifiers, used by Alembic.
revision = '90b724f11869'
down_revision = '58d7e7735cb0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
   op.add_column('user', sa.Column('date_created', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
